"use client";
import { useState } from 'react';
type Option={id:string;label:string};
async function call(url:string,method:string,body:any,isForm=false){const r=await fetch(url,{method,headers:isForm?undefined:{'content-type':'application/json'},body:isForm?body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j}
export function PortalActions({kind,section,services=[],markets=[]}:{kind:'customer'|'photographer'|'business';section:string;services?:Option[];markets?:Option[]}){const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);async function run(fn:()=>Promise<any>){setBusy(true);setMessage('');try{await fn();setMessage('Saved. Refresh the page to see the updated record.')}catch(e){setMessage(e instanceof Error?e.message:'Request failed')}finally{setBusy(false)}}
if(kind==='photographer'&&section==='availability')return <form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>call('/api/lens-life/photographer/availability','POST',{startsAt:f.get('startsAt'),endsAt:f.get('endsAt'),type:f.get('type'),notes:f.get('notes')}))}}><h3>Add availability</h3><label>From<input name="startsAt" type="datetime-local" required/></label><label>To<input name="endsAt" type="datetime-local" required/></label><label>Type<select name="type"><option value="available">Available</option><option value="unavailable">Unavailable</option></select></label><label>Notes<input name="notes"/></label><button disabled={busy}>Save availability</button>{message&&<p>{message}</p>}</form>;
if(kind==='photographer'&&section==='services')return <form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>call('/api/lens-life/photographer/services','POST',{serviceOfferingId:f.get('service'),enabled:true,experienceLevel:f.get('level')}))}}><h3>Add or enable a service</h3><label>Service<select name="service" required>{services.map(x=><option value={x.id} key={x.id}>{x.label}</option>)}</select></label><label>Experience<select name="level"><option>experienced</option><option>specialist</option><option>developing</option></select></label><button disabled={busy}>Save service</button>{message&&<p>{message}</p>}</form>;
if(kind==='photographer'&&section==='service-areas')return <form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>call('/api/lens-life/photographer/service-areas','POST',{marketId:f.get('market')||undefined,postcodePrefix:f.get('postcodePrefix')||undefined,radiusMiles:f.get('radius')?Number(f.get('radius')):undefined,notes:f.get('notes')||undefined}))}}><h3>Add service area</h3><label>Market<select name="market"><option value="">Postcode-based</option>{markets.map(x=><option value={x.id} key={x.id}>{x.label}</option>)}</select></label><label>Postcode prefix<input name="postcodePrefix" placeholder="DA, SE, L"/></label><label>Radius miles<input name="radius" type="number" min="1" max="150"/></label><label>Travel notes<input name="notes"/></label><button disabled={busy}>Save area</button>{message&&<p>{message}</p>}</form>;
if(kind==='photographer'&&section==='offers')return <form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>call(`/api/lens-life/photographer/offers/${f.get('offerId')}/respond`,'POST',{decision:f.get('decision'),notes:f.get('notes')}))}}><h3>Respond to an offer</h3><label>Offer ID<input name="offerId" required/></label><label>Decision<select name="decision"><option value="accept">Accept</option><option value="decline">Decline</option></select></label><label>Notes<input name="notes"/></label><button disabled={busy}>Submit response</button>{message&&<p>{message}</p>}</form>;
if(kind==='photographer'&&section==='bookings')return <form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>call(`/api/lens-life/photographer/jobs/${f.get('jobId')}/status`,'POST',{status:f.get('status')}))}}><h3>Update job progress</h3><label>Job ID<input name="jobId" required/></label><label>Status<select name="status"><option value="checked_in">Checked in</option><option value="shooting">Shoot started</option><option value="shoot_complete">Shoot completed</option></select></label><button disabled={busy}>Update job</button>{message&&<p>{message}</p>}</form>;
if(kind==='photographer'&&section==='uploads')return <form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>call('/api/lens-life/photographer/uploads','POST',f,true))}}><h3>Upload completed gallery</h3><label>Deliverable ID<input name="deliverableId" required/></label><label>Images<input name="files" type="file" accept="image/jpeg,image/png,image/webp,image/tiff" multiple required/></label><button disabled={busy}>Upload for quality review</button>{message&&<p>{message}</p>}</form>;
if(kind==='photographer'&&section==='documents')return <form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>call('/api/lens-life/photographer/documents','POST',f,true))}}><h3>Upload compliance document</h3><label>Document type<select name="documentType"><option value="public_liability">Public liability</option><option value="right_to_work">Right to work</option><option value="dbs">DBS</option><option value="identity">Identity</option></select></label><label>File<input name="file" type="file" required/></label><button disabled={busy}>Upload document</button>{message&&<p>{message}</p>}</form>;
if(kind==='photographer'&&section==='payouts')return <div className="form"><h3>Stripe payout account</h3><p>Connect or refresh your payout account. Live onboarding only runs when payout integration is enabled.</p><button disabled={busy} onClick={()=>run(async()=>{const j=await call('/api/lens-life/photographer/connect','POST',{});location.href=j.url})}>Connect payout account</button>{message&&<p>{message}</p>}</div>;
if(kind==='customer'&&section==='support')return <form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>call('/api/lens-life/customer/support','POST',{subject:f.get('subject'),description:f.get('description'),bookingId:f.get('bookingId')||undefined,category:f.get('category')}))}}><h3>Open a support case</h3><label>Subject<input name="subject" required/></label><label>Booking ID<input name="bookingId"/></label><label>Category<select name="category"><option value="general">General</option><option value="booking">Booking</option><option value="delivery">Delivery</option><option value="payment">Payment</option></select></label><label>Description<textarea name="description" required/></label><button disabled={busy}>Open case</button>{message&&<p>{message}</p>}</form>;
if(kind==='customer'&&section==='reviews')return <form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>call('/api/lens-life/customer/reviews','POST',{bookingId:f.get('bookingId'),rating:Number(f.get('rating')),title:f.get('title')||undefined,body:f.get('body')||undefined}))}}><h3>Leave a review</h3><label>Completed booking ID<input name="bookingId" required/></label><label>Rating<select name="rating">{[5,4,3,2,1].map(x=><option key={x}>{x}</option>)}</select></label><label>Title<input name="title"/></label><label>Review<textarea name="body"/></label><button disabled={busy}>Submit review</button>{message&&<p>{message}</p>}</form>;
if(kind==='customer'&&section==='galleries')return <form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>call(`/api/lens-life/customer/gallery/${f.get('bookingId')}/approve`,'POST',{}))}}><h3>Approve delivered gallery</h3><label>Booking ID<input name="bookingId" required/></label><button disabled={busy}>Approve gallery</button>{message&&<p>{message}</p>}</form>;
if(kind==='business'&&section==='bookings')return <form className="form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);run(()=>call('/api/lens-life/business/bookings','POST',{serviceOfferingId:f.get('service'),startsAt:f.get('startsAt'),siteId:f.get('siteId')||undefined,templateId:f.get('templateId')||undefined,notes:f.get('notes')||undefined}))}}><h3>Create business booking</h3><label>Service<select name="service" required>{services.map(x=><option value={x.id} key={x.id}>{x.label}</option>)}</select></label><label>Date & time<input name="startsAt" type="datetime-local" required/></label><label>Site ID<input name="siteId"/></label><label>Template ID<input name="templateId"/></label><label>Notes<textarea name="notes"/></label><button disabled={busy}>Create booking</button>{message&&<p>{message}</p>}</form>;
return null}
