import 'server-only';import { adminDb } from '@/lib/supabase/admin';import type { Actor } from '@/lib/roles';
export type Section={table:string;select?:string;filter?:string;order?:string};
export const customerSections:Record<string,Section>={bookings:{table:'ll_bookings',filter:'customer_id',order:'created_at'},payments:{table:'ll_payments',select:'id,booking_id,status,amount_pence,currency,settled_at,created_at',order:'created_at'},support:{table:'ll_support_cases',filter:'customer_id',order:'created_at'},reviews:{table:'ll_reviews',filter:'customer_id',order:'created_at'}};
export const photographerSections:Record<string,Section>={onboarding:{table:'ll_photographers'},services:{table:'ll_photographer_services',filter:'photographer_id'},'service-areas':{table:'ll_photographer_service_areas',filter:'photographer_id'},availability:{table:'ll_photographer_availability',filter:'photographer_id',order:'starts_at'},offers:{table:'ll_job_offers',filter:'photographer_id',order:'offered_at'},bookings:{table:'ll_booking_assignments',filter:'photographer_id',order:'assigned_at'},payouts:{table:'ll_photographer_payouts',filter:'photographer_id',order:'scheduled_for'},documents:{table:'ll_photographer_documents',filter:'photographer_id',order:'created_at'},equipment:{table:'ll_photographer_equipment',filter:'photographer_id'},portfolio:{table:'ll_photographer_portfolio_items',filter:'photographer_id'},training:{table:'ll_training_assignments',filter:'photographer_id'},quality:{table:'ll_quality_reviews',filter:'photographer_id'},reviews:{table:'ll_reviews',filter:'photographer_id'},support:{table:'ll_support_cases',filter:'photographer_id',order:'created_at'}};
export const businessSections:Record<string,Section>={sites:{table:'ll_organisation_sites'},templates:{table:'ll_business_booking_templates',filter:'business_account_id'},bookings:{table:'ll_bookings',filter:'business_account_id',order:'created_at'},contracts:{table:'ll_business_contracts',filter:'business_account_id'},billing:{table:'ll_payments',order:'created_at'},reports:{table:'ll_conversion_events',order:'occurred_at'}};
export async function scopedRows(section:Section,actor:Actor,kind:'customer'|'photographer'|'business'){
 const db=adminDb(); let q=db.from(section.table).select(section.select||'*').limit(100); const id=kind==='customer'?actor.customerId:kind==='photographer'?actor.photographerId:actor.businessAccountId;
 if(section.filter&&id)q=q.eq(section.filter,id); if(section.table==='ll_photographers'&&actor.photographerId)q=q.eq('id',actor.photographerId);
 if(kind==='customer'&&section.table==='ll_payments'&&actor.customerId){const b=await db.from('ll_bookings').select('id').eq('customer_id',actor.customerId);q=q.in('booking_id',(b.data||[]).map(x=>x.id));}
 if(kind==='business'&&section.table==='ll_organisation_sites'&&actor.businessAccountId){const ba=await db.from('ll_business_accounts').select('organisation_id').eq('id',actor.businessAccountId).single();q=q.eq('organisation_id',ba.data!.organisation_id)}
 if(kind==='business'&&section.table==='ll_payments'&&actor.businessAccountId){const b=await db.from('ll_bookings').select('id').eq('business_account_id',actor.businessAccountId);q=q.in('booking_id',(b.data||[]).map(x=>x.id));}
 if(section.order) q=q.order(section.order,{ascending:false}); const {data,error}=await q;if(error)throw error;return (data||[]) as unknown as Record<string,unknown>[];
}
